### ISSUE TITLE
lack 1 luac File

### ISSUE THREAD

**Issue by dlnn** [TheLostTree/YSLua#1]
- How to decompile this luac file  gsVer 2.6.
[script.zip](https://github.com/TheLostTree/YSLua/files/8417110/script.zip)

**Comment by TheLostTree** [comment]
[script.txt](https://github.com/TheLostTree/YSLua/files/8477711/script.txt)


here's the decompiled output

looks to be windseed? thats not something in the client

anyhow the bytes it returns might also be luac but i dont really know
